package io.protostuff.example.search;

import com.google.common.util.concurrent.Futures;
import com.google.common.util.concurrent.ListenableFuture;

import java.util.Arrays;

/**
 * Service code generation example.
 * Interface {@code SearchService} is generated by protostuff-maven-plugin.
 *
 * @author Konstantin Shchepanovskyi
 */
public class DummySearchService implements SearchService {

    @Override
    public ListenableFuture<SearchResponse> basicSearch(BasicSearchRequest request) {
        SearchResponse response = new SearchResponse();
        response.setResultList(Arrays.asList(
                "result 1",
                "result 2"
        ));
        return Futures.immediateFuture(response);
    }

    @Override
    public ListenableFuture<SearchResponse> extendedSearch(ExtendedSearchRequest request) {
        SearchResponse response = new SearchResponse();
        response.setResultList(Arrays.asList(
                "result 1",
                "result 2",
                "result 3"
        ));
        return Futures.immediateFuture(response);
    }
}
